name: Build cashd-local

on:
  release:
    types: [published]

jobs:
    build-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install briefcase

            - name: Build Windows installer
              run: |
                cd D:\a\cashd\cashd\cashd-local
                briefcase build windows
                briefcase package windows --adhoc-sign

            - name: Upload Windows installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-windows-installer
                path: D:\a\cashd\cashd\cashd-local\dist\*.msi

    build-ubuntu:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y python3-dev python3-pip build-essential
                sudo apt-get install -y git pkg-config libgirepository1.0-dev libgirepository-2.0-dev libcairo2-dev gir1.2-gtk-3.0 libcanberra-gtk3-module
                python -m pip install --upgrade pip
                pip install briefcase

            - name: Build Linux .deb installer
              run: |
                cd $GITHUB_WORKSPACE/cashd-local
                briefcase build linux
                briefcase package linux --adhoc-sign

            - name: Upload .deb installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-deb-installer
                path: $GITHUB_WORKSPACE/cashd-local/dist/*.deb

    build-fedora:
        runs-on: ubuntu-latest
        container:
            image: fedora:latest

        steps:
            - name: Install dependencies
              run: |
                dnf install -y python3 python3-pip python3-devel gcc make
                dnf install -y git pkg-config gobject-introspection-devel cairo-gobject-devel gtk3 libcanberra-gtk3
                pip3 install --upgrade pip
                pip3 install briefcase
                dnf install -y git

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Linux .rpm installer
              run: |
                cd $GITHUB_WORKSPACE/cashd-local
                briefcase build linux
                briefcase package linux --adhoc-sign

            - name: Upload .rpm installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-rpm-installer
                path: $GITHUB_WORKSPACE/cashd-local/dist/*.rpm
