name: Build cashd-local

on:
  release:
    types: [published]

jobs:
    build-windows:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ../cashd-local
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                path: cashd-local

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install briefcase

            - name: Build Windows installer
              run: briefcase build windows

            - name: Package Windows installer
              run: briefcase package windows --adhoc-sigh

            - name: Upload Windows installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-windows-installer
                path: ../cashd-local/dist/*.msi

    build-ubuntu:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./cashd-local
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y python3-dev python3-pip build-essential
                sudo apt-get install -y git pkg-config python3-dev libgirepository2.0-dev libcairo2-dev gir1.2-gtk-3.0 libcanberra-gtk3-module
                python -m pip install --upgrade pip
                pip install briefcase

            - name: Build Linux .deb installer
              run: |
                cd cashd-local
                briefcase create
                briefcase build linux

            - name: Package Linux .deb installer
              run: briefcase package linux

            - name: Upload .deb installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-ubuntu-installer
                path: ../cashd-local/linux/installer/*.deb

    build-fedora:
        runs-on: ubuntu-latest
        container:
            image: fedora:latest
        defaults:
            run:
                working-directory: cashd-local
        steps:
            - name: Install dependencies
              run: |
                dnf install -y python3 python3-pip python3-devel gcc make
                pip3 install --upgrade pip
                pip3 install briefcase
                dnf install -y git

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                path: cashd-local

            - name: Build Linux .rpm installer
              run: briefcase build linux

            - name: Package Linux .rpm installer
              run: briefcase package linux

            - name: Upload .rpm installer
              uses: actions/upload-artifact@v4
              with:
                name: cashd-fedora-installer
                path: /github/workspace/cashd-local/linux/installer/*.rpm
